module Euler029 where
import EulerLib
import qualified SortedList as S

------------------------------------------------------------------------------
-- 29. How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

prob29 :: Integer -> Int -> Int
prob29 m n =
  length $
  foldl1 S.union $
  map (\a -> map (\b -> a ^ b) [2 .. n]) [2 .. m]
-- prob29 100 = 9183
-- prob29 200 = 37774

main :: IO String
main = return $ show $ prob29 100 100

{-
618 duplicates

All duplicates are when 'a' is a member of:
[2,3,4,5,6,7,8,9,10,16,25,27,32,36,49,64,81,100]

2^(2*a) = 4^a
2^(3*a) = 8^a

powers up to 100:
2: [2, 4, 8, 16, 32, 64]
3: [3, 9, 27, 81]
4: [4, 16, 64]
5: [5, 25]
6: [6, 36]
7: [7, 49]
8: [8, 64]
9: [9, 81]
10: [10, 100]

2^4 = 4^2
2^6 = 4^3 = 8^2
3^4 = 9^2
2^8 = 4^4
2^9 = 8^3
3^6 = 9^3
2^10 = 4^5
4^6 = 8^4
3^8 = 9^4
3^10 = 9^5
4^9 = 8^6
-}